# Generated by Django 3.2.8 on 2021-10-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qu_liq_m3day', models.FloatField()),
                ('d_i_m', models.FloatField()),
                ('d_o_m', models.FloatField()),
                ('h', models.FloatField()),
                ('p_head', models.FloatField()),
                ('t_head', models.FloatField()),
                ('wct', models.FloatField()),
                ('rp', models.FloatField()),
                ('results', models.CharField(max_length=1000000)),
            ],
        ),
    ]
