# Generated by Django 3.2.8 on 2021-11-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasankabir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='absep',
            field=models.FloatField(default=2.54),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='md1',
            field=models.FloatField(default=1400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='md2',
            field=models.FloatField(default=1800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='md3',
            field=models.FloatField(default=2400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='tvd1',
            field=models.FloatField(default=1400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='tvd2',
            field=models.FloatField(default=1800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='tvd3',
            field=models.FloatField(default=2400),
            preserve_default=False,
        ),
    ]
