# Generated by Django 3.2.8 on 2021-11-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasankabir', '0002_auto_20211104_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='h',
        ),
    ]
