# Generated by Django 3.2.8 on 2021-11-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasankabir', '0004_auto_20211109_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='d_i_m',
        ),
        migrations.RemoveField(
            model_name='database',
            name='d_o_m',
        ),
        migrations.AddField(
            model_name='database',
            name='d_i_1',
            field=models.FloatField(default=73),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='d_i_2',
            field=models.FloatField(default=73),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='d_i_3',
            field=models.FloatField(default=73),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='d_o_1',
            field=models.FloatField(default=142),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='d_o_2',
            field=models.FloatField(default=142),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='d_o_3',
            field=models.FloatField(default=142),
            preserve_default=False,
        ),
    ]
